---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - security.altlinux.org
  resources:
  - altimageupdatepolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - security.altlinux.org
  resources:
  - altimageupdatepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - security.altlinux.org
  resources:
  - altimageupdatepolicies/status
  verbs:
  - get
  - patch
  - update
